jobs:
  - name: rbac-csv-upload-integration
    max_in_flight: 1
    serial: true
    plan:
      - get: rbac-csv
        trigger: true
        passed:
        - rbac-csv-upload-qa
      - get: aws-common-infrastructure
        passed:
          - rbac-csv-upload-qa
      - .: (( inject meta.plan.terraform-output-common ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.rbac-csv-upload ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
