jobs:
  - name: rbac-csv-upload-preprod
    max_in_flight: 1
    serial: true
    plan:
      - get: rbac-csv
        trigger: true
        passed:
        - rbac-csv-upload-qa
      - get: aws-common-infrastructure
      - .: (( inject meta.plan.terraform-output ))
        config:
          params:
            TF_WORKSPACE: preprod
      - .: (( inject meta.plan.rbac-csv-upload ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci

  - name: object-tagging-preprod
    max_in_flight: 1
    serial: true
    plan:
      - get: rbac-csv
        trigger: true
        passed:
          - rbac-csv-upload-integration
      - put: meta
        resource: meta-preprod
      - get: aws-common-infrastructure
      - .: (( inject meta.plan.terraform-output ))
        config:
          params:
            TF_WORKSPACE: preprod
      - .: (( inject meta.plan.object-tagging-batch ))
        config:
          params:
            BATCH_JOB_DEFINITION: pdm_object_tagger_job
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            DATA_S3_PREFIX: "data/uc"
            CSV_PREFIX: "component/rbac"
            FILE_NAME: "data_classification.csv"
