jobs:
  - name: production
    max_in_flight: 1
    plan:
      - get: dataworks-aws-s3-object-tagger
        trigger: true
        passed:
          - preprod
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'production'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'production'
